export const siteConfig = {
  name: "Semt Döviz",
  legalName: "Semt Döviz ve Altın Ticaret Sınırlı Yetkili Müessese A.Ş.",
  domain: "semtdoviz.com",
  url: "https://semtdoviz.com",
  description:
    "Semt Döviz; T.C. Hazine ve Maliye Bakanlığı onaylı B Grubu Yetkili Müessese olarak şeffaf kurlar ve güvenilir hizmetle döviz ve altın alım-satımı sunar. Güncel USD, EUR, GBP ve CHF kurlarını canlı takip edin.",
  shortDescription: "Yetkili döviz ve altın müessesesi.",
  tagline: "Güvenin adresi, kurun şeffaf adresi.",
  phone: "+90 212 000 00 00",
  phoneDisplay: "0212 000 00 00",
  whatsapp: "+90 532 000 00 00",
  email: "info@semtdoviz.com",
  address: {
    street: "Cemil Meriç Mah. Alemdağ Cd. Kızılırmak İş Hanı A Blok No:281/1",
    district: "Ümraniye",
    city: "İstanbul",
    postalCode: "",
    country: "TR",
  },
  hours: {
    weekdays: "09:00 – 19:00",
    saturday: "10:00 – 17:00",
    sunday: "Kapalı",
  },
  social: {
    instagram: "https://instagram.com/semtdoviz",
    x: "https://x.com/semtdoviz",
  },
  legal: {
    licenseAuthority: "T.C. Hazine ve Maliye Bakanlığı",
    licenseType: "B Grubu Yetkili Müessese",
    licenseDate: "10.01.2020",
    taxOffice: "Alemdağ Vergi Dairesi",
    taxNo: "7610009806",
    tradeRegistryNo: "3813-8",
    mersisNo: "0761000990600019",
  },
  keywords: [
    "döviz bürosu",
    "semt döviz",
    "güncel döviz kuru",
    "dolar kuru",
    "euro kuru",
    "sterlin kuru",
    "altın alım satım",
    "ümraniye döviz",
    "istanbul döviz bürosu",
    "canlı döviz kurları",
  ],
} as const;
